// Données fictives pour le développement et les démonstrations
import { Course, School, Review } from "./types";

export const mockSchools: School[] = [
  {
    id: "school-1",
    name: "Academy du Numérique",
    description:
      "Centre de formation spécialisé dans les métiers du numérique et de l'informatique. Nos formateurs sont tous des professionnels en activité.",
    logo_url: null,
    location: "Paris 11ème",
    contact_email: "contact@academy-numerique.fr",
    website_url: "https://academy-numerique.fr",
    is_premium: true,
    is_verified: true,
    created_at: "2024-01-15T10:00:00Z",
    avg_rating: 4.7,
  },
  {
    id: "school-2",
    name: "LinguaWorld",
    description:
      "École de langues avec des méthodes immersives et des professeurs natifs. Cours disponibles pour tous niveaux.",
    logo_url: null,
    location: "Lyon 2ème",
    contact_email: "info@linguaworld.fr",
    website_url: null,
    is_premium: false,
    is_verified: true,
    created_at: "2024-02-01T10:00:00Z",
    avg_rating: 4.5,
  },
  {
    id: "school-3",
    name: "Business Excellence",
    description:
      "Formation professionnelle en commerce, marketing digital et gestion d'entreprise. MBA et certifications reconnues.",
    logo_url: null,
    location: "Bordeaux",
    contact_email: "formation@business-excellence.fr",
    website_url: "https://business-excellence.fr",
    is_premium: true,
    is_verified: true,
    created_at: "2024-01-20T10:00:00Z",
    avg_rating: 4.3,
  },
];

export const mockCourses: Course[] = [
  {
    id: "course-1",
    school_id: "school-1",
    title: "Développement Web Full-Stack React & Node.js",
    description:
      "Maîtrisez les technologies les plus demandées sur le marché : React, Node.js, PostgreSQL et déploiement cloud. Formation intensive conçue pour les reconversions professionnelles.",
    category: "informatique",
    duration: "6 mois (840h)",
    format: "hybrid",
    price: 4500,
    schedule_details:
      "Lundi au Vendredi, 9h-17h (présentiel) + 2 soirs/semaine en ligne",
    prerequisites: "Bases en logique de programmation souhaitées",
    certification: "Certification RNCP Niveau 6 - Développeur Web",
    seats_available: 8,
    is_active: true,
    created_at: "2024-03-01T10:00:00Z",
    school: mockSchools[0],
    avg_rating: 4.8,
    review_count: 24,
  },
  {
    id: "course-2",
    school_id: "school-1",
    title: "Data Science & Machine Learning avec Python",
    description:
      "Apprenez l'analyse de données, la visualisation et les algorithmes de Machine Learning. Projets concrets sur des datasets réels d'entreprises partenaires.",
    category: "informatique",
    duration: "4 mois (480h)",
    format: "online",
    price: 3200,
    schedule_details: "100% en ligne, à votre rythme + sessions live hebdomadaires le samedi",
    prerequisites: "Notions de Python et statistiques de base",
    certification: "Certificat Data Scientist - Reconnu par France Compétences",
    seats_available: 15,
    is_active: true,
    created_at: "2024-03-05T10:00:00Z",
    school: mockSchools[0],
    avg_rating: 4.6,
    review_count: 18,
  },
  {
    id: "course-3",
    school_id: "school-2",
    title: "Anglais Professionnel - Niveau Intermédiaire à Avancé",
    description:
      "Boostez votre anglais professionnel avec des mises en situation réelles : présentations, négociations, emails et réunions en anglais. Professeurs anglophones natifs.",
    category: "langues",
    duration: "3 mois (120h)",
    format: "presential",
    price: 1800,
    schedule_details: "Mardi et Jeudi 18h30-20h30, Samedi 9h-12h",
    prerequisites: "Niveau B1 minimum (test gratuit à l'inscription)",
    certification: "Préparation TOEIC incluse",
    seats_available: 12,
    is_active: true,
    created_at: "2024-03-10T10:00:00Z",
    school: mockSchools[1],
    avg_rating: 4.5,
    review_count: 31,
  },
  {
    id: "course-4",
    school_id: "school-2",
    title: "Espagnol Débutant - Méthode Accélérée",
    description:
      "Partez de zéro et atteignez un niveau conversationnel en 3 mois grâce à notre méthode immersive et nos outils digitaux exclusifs.",
    category: "langues",
    duration: "3 mois (90h)",
    format: "hybrid",
    price: 990,
    schedule_details: "Mercredi 18h-20h + e-learning en autonomie",
    prerequisites: "Aucun prérequis",
    certification: "Attestation de niveau FormaFind",
    seats_available: 20,
    is_active: true,
    created_at: "2024-03-12T10:00:00Z",
    school: mockSchools[1],
    avg_rating: 4.4,
    review_count: 15,
  },
  {
    id: "course-5",
    school_id: "school-3",
    title: "Marketing Digital & Réseaux Sociaux",
    description:
      "Maîtrisez Google Ads, Facebook Ads, SEO et la création de contenu engageant. Apprenez à piloter des campagnes rentables pour des entreprises ou votre propre activité.",
    category: "commerce",
    duration: "2 mois (160h)",
    format: "online",
    price: 1490,
    schedule_details: "100% en ligne, accessible 24h/24 pendant 6 mois",
    prerequisites: "Maîtrise basique d'internet et des réseaux sociaux",
    certification: "Certification Google Ads incluse",
    seats_available: null,
    is_active: true,
    created_at: "2024-03-15T10:00:00Z",
    school: mockSchools[2],
    avg_rating: 4.3,
    review_count: 42,
  },
  {
    id: "course-6",
    school_id: "school-3",
    title: "Gestion de Projet Agile & Scrum",
    description:
      "Devenez Chef de Projet Agile certifié. Maîtrisez les méthodes Scrum, Kanban et les outils comme Jira et Trello pour gérer des projets complexes.",
    category: "gestion",
    duration: "1 mois (40h)",
    format: "presential",
    price: 1200,
    schedule_details: "Semaines intensives du Lundi au Vendredi, 4 sessions par an",
    prerequisites: "Expérience en gestion d'équipe recommandée",
    certification: "Certification PSM I (Professional Scrum Master)",
    seats_available: 6,
    is_active: true,
    created_at: "2024-03-18T10:00:00Z",
    school: mockSchools[2],
    avg_rating: 4.6,
    review_count: 19,
  },
];

export const mockReviews: Review[] = [
  {
    id: "review-1",
    course_id: "course-1",
    user_id: "user-1",
    rating: 5,
    comment:
      "Formation exceptionnelle ! Les formateurs sont des professionnels qui partagent des expériences réelles. J'ai trouvé un emploi de développeur 2 semaines après la fin de la formation.",
    created_at: "2024-04-10T14:30:00Z",
    profile: { id: "user-1", email: "sarah@test.fr", full_name: "Sarah M.", avatar_url: null, role: "apprenant", school_id: null, created_at: "" },
  },
  {
    id: "review-2",
    course_id: "course-1",
    user_id: "user-2",
    rating: 5,
    comment:
      "Le format hybride est parfait. Beaucoup de pratique, des projets concrets et une super ambiance de groupe. Je recommande à 100%.",
    created_at: "2024-04-20T10:15:00Z",
    profile: { id: "user-2", email: "thomas@test.fr", full_name: "Thomas K.", avatar_url: null, role: "apprenant", school_id: null, created_at: "" },
  },
  {
    id: "review-3",
    course_id: "course-1",
    user_id: "user-3",
    rating: 4,
    comment:
      "Très bonne formation, contenu à jour et formateurs disponibles. Quelques modules pourraient être plus approfondis mais globalement excellent.",
    created_at: "2024-05-05T09:00:00Z",
    profile: { id: "user-3", email: "marie@test.fr", full_name: "Marie D.", avatar_url: null, role: "apprenant", school_id: null, created_at: "" },
  },
];
